package com.example.dto

object Dropdown {

    val bajaj = listOf(
        "Acko General Insurance Limited",
        "Acko General Insurance Limited",
        "Bajaj Allianz Genaral Insurance Company Ltd",
        "Bajaj Allianz General Insurance Co Ltd",
        "Bharti AXA General Insurance Company Limited",
        "Cholamandalam MS General Insurance Company Limited",
        "DHFL General Insurance Limited",
        "DHFL General Insurance Limited",
        "Edelweiss General Insurance Company Limited",
        "Future Generali India Insurance Company Limited",
        "Go Digit General Insurance Limited",
        "Go Digit General Insurance Limited",
        "HDFC ERGO General Insurance Company Limited",
        "ICICI Lombard General Insurance Company Limited",
        "IFFCO Tokio General Insurance Company Limited",
        "KOTAK MAHINDRA GENERAL INSURANCE",
        "Kotak Mahindra General Insurance Company ltd",
        "L&T General Insurance Company Limited",
        "LIBERTY GENERAL INSURANCE",
        "Liberty general insurance limited",
        "Magma HDI General Insurance Company Limited",
        "National Insurance Company Limited",
        "Navi General Insurance Ltd",
        "Raheja QBE General Insurance Company Limited",
        "Reinsurance Inward",
        "Reliance General Insurance Company Limited",
        "Royal Sundaram General Insurance Co. Limited",
        "SBI General Insurance Company Limited",
        "Shriram General Insurance Company Limited",
        "Tata AIG General Insurance Company Limited",
        "The New India Assurance Company Limited",
        "The Oriental Insurance Company Limited",
        "United India Insurance Company Limited",
        "Universal Sompo General Insurance Company"
    )

    val icici = listOf(
        "BHARATI AXA GENERAL INSURANCE CO.LTD.",
        "ICICI LOMBARD GENERAL INSURANCE COMPANY LTD.",
        "ACKO GENERAL INSURANCE LIMITED",
        "UNIVERSAL SOMPO GENERAL INSURANCE CO. LTD.",
        "LIBERTY VIDEOCON GENERAL INSURANCE COMPANY LIMITED",
        "NEW INDIA ASSURANCE COMPANY LTD.",
        "UNITED INDIA INSURANCE COMPANY LTD.",
        "NATIONAL INSURANCE COMPANY LIMITED",
        "ORIENTAL INSURANCE COMPANY LTD.",
        "RELIANCE GENERAL INSURANCE COMPANY LTD.",
        "ROYAL SUNDARAM GENERAL INSURANCE COMPANY LIMITED",
        "TATA AIG GENERAL INSURANCE COMPANY LIMITED",
        "IFFCO TOKIO GENERAL INSURANCE COMPANY LIMITED",
        "BAJAJ ALLIANZ GENERAL INSURANCE COMPANY LIMITED",
        "CHOLAMANDALAM MS GENERAL INSURANCE COMPANY LTD.",
        "KOTAK MAHINDRA GENERAL INSURANCE",
        "SBI GENERAL INSURANCE COMPANY LIMITED",
        "SHRIRAM GENERAL INSURANCE COMPANY",
        "DHFL GENERAL INSURANCE LIMITED",
        "EDELWEISS GENERAL INSURANCE COMPANY",
        "KOTAK GENERAL INSURANCE COMPANY LIMITED",
        "KOTAK GENERAL INSURANCE COMPANY LIMITED",
        "ROYAL SUNDARAM ALLIANCE INSURANCE COMPANY LTD",
        "HDFC ERGO GENERAL INSURANCE COMPANY LTD.",
        "FUTURE GENERALI INDIA INSURANCE CO LTD.",
        "UNIVERSAL SOMPO GENERAL INSURANCE CO. LTD.",
        "UNIVERSAL SOMPO GENERAL INSURANCE CO. LTD.",
        "L&T GENERAL INSURANCE COMPANY LIMITED",
        "RAHEJA QBE GENERAL INSURANCE COMPANY LIMITED",
        "KOTAK GENERAL INSURANCE"
    )

    val tataAig = listOf(
        "BAJAJ ALLIANZ GENERAL INSURANCE CO.LTD",
        "ICICI LOMBARD GENERAL INSURANCE CO. LTD.",
        "APOLLO MUNICH (AMHI)",
        "IFFCO TOKIO GENERAL INSURANCE CO. LTD.",
        "NATIONAL INSURANCE CO.LTD.",
        "GO DIGIT GENERAL INSURANCE CO LTD",
        "THE NEW INDIA ASSURANCE CO. LTD.",
        "THE ORIENTAL INSURANCE CO. LTD.",
        "RELIANCE GENERAL INSURANCE CO.LTD.",
        "DIRECTORATE OF INSURANCE (GIF),GOVT. OF MAHA",
        "ROYAL SUNDARAM ALLIANCE INSURANCE CO.LTD.",
        "ENDURANCE",
        "UNITED INDIA INSURANCE CO.LTD.",
        "CHOLAMANDALAM MS GENERAL INSURANCE CO.LTD.",
        "GENERAL INSURANCE CORPORATION OF INDIA",
        "HDFC ERGO GENERAL INSURANCE CO.LTD.",
        "EXPORT CREDIT GUARANTEE CORPORATION OF INDIA LTD",
        "AGRICULTURE INSURANCE CO. OF INDIA LTD.",
        "STAR HEALTH AND ALLIED INSURANCE COMPANY LIMITED",
        "L&T GENERAL INSURANCE CO. LTD.",
        "MAGMA HDI GENERAL INSURANCE CO LTD",
        "FUTURE GENERALI INDIA INSURANCE COMPANY LIMITED",
        "MITSUI INSURANCE",
        "TATA AIG GENERAL INSURANCE CO.LTD.",
        "UNIVERSAL SOMPO GENERAL INSURANCE CO.LTD.",
        "Maharashtra Government Insurance Fund",
        "BHARTI AXA GENERAL INSURANCE COMPANY LIMITED",
        "RAHEJA QBE GENERAL INSURANCE COMPANY LIMITED",
        "SBI GENERAL INSURANCE COMPANY LIMITED",
        "THE GOVT. OF GUJARAT INSURANCE FUND",
        "LIBERTY VIDEOCON GENERAL INSURANCE COMPANY LTD.",
        "SHRIRAM GENERAL INSURANCE COMPANY LIMITED",
        "Religare Health Insurance Company Limited",
        "MAX BUPA HEALTH INSURANCE COMPANY LTD.",
        "CignaTTK Health Insurance Company Limited",
        "Aditya Birla Health Insurance Company Limited",
        "ACKO General Insurance Ltd",
        "KOTAK MAHINDRA GENERAL INSURANCE COMPANY LTD",
        "EDELWEISS GENERAL INSURANCE COMPANY LIMITED",
        "DHFL COCO GENERAL INSURANCE LIMITED",
        "MAHARASHTRA STATE INSURANCE FUND",
        "HDFC ERGO HEALTH INSURANCE LTD.",
        "LIBERTY GENERAL INSURANCE LTD.",
        "MANIPALCIGNA HEALTH INSURANCE CO LTD",
        "RELIANCE HEALTH INSURANCE LTD.",
        "CARE HEALTH INSURANCE LTD"
    )

}
